import System.Random

dutch_ijs =
  [ "Asjemenou!"
  , "Deksels!"
  , "Drommels!"
  , "Gaaf!"
  , "Gers!"
  , "Gossie!"
  , "Goud!"
  , "Grutjes!"
  , "Hatsikidee!"
  , "Heftig!"
  , "Hupsakee!"
  , "Jandoedel!"
  , "Jemig!"
  , "Jeminee!"
  , "Joechei!"
  , "Joepie!"
  , "Jolijt!"
  , "Jottem!"
  , "Lauw!"
  , "Mieters!"
  , "Plopperdeplop!"
  , "Potjandorie!"
  , "Potvolkoffie!"
  , "Puik!"
  , "Reuze!"
  , "Sapperdeflap!"
  , "Sapperloot!"
  , "Sodeju!"
  , "Sodeknetter!"
  , "Tjakka!"
  , "Tjongejonge!"
  , "Tof!"
  , "Verdraaid!"
  , "Verhip!"
  , "Verrek!"
  , "Vet!"
  , "Waanzinnig!"
  , "Wauw!"
  , "Wreed!"
  ]

ijs =
  [ "Abracadabra!"
  , "A mind is a terrible thing to waste."
  , "All good in the hood!"
  , "All hands on deck!"
  , "All or nothing!"
  , "All righty!"
  , "All you need is love."
  , "Allah Akbar!"
  , "Aloha!"
  , "Alrighty then!"
  , "Alrighty!"
  , "Amen."
  , "Amirite?"
  , "Attaboy!"
  , "Awesome!"
  , "Aww!"
  , "Ba da bing ba da boom!"
  , "Ba dum tish!"
  , "Bam!"
  , "Bejesus!"
  , "Bingo!"
  , "Bish bash bosh!"
  , "Bitchin'!"
  , "Bite my shiny metal ass!"
  , "Blimey!"
  , "Blow me over!"
  , "Blow me tight!"
  , "Bombs away!"
  , "Boo-yah!"
  , "Boom shaka laka!"
  , "Booyah!"
  , "Bottoms up!"
  , "Bravissimo!"
  , "Brilliant!"
  , "Butter my butt and call me a biscuit!"
  , "By Grabthar's hammer!"
  , "By golly!"
  , "By the rings of Saturn!"
  , "By the suns of Warvan!"
  , "Calm your tits!"
  , "Caramba!"
  , "Carpe diem."
  , "Centerfold!"
  , "Check!"
  , "Cheerioh!"
  , "Cheers!"
  , "Clickety clackety!"
  , "Cockadoodledoo!"
  , "Color me surprised!"
  , "Cool bananas!"
  , "Cool!"
  , "Cootchie-cootchie-coo!"
  , "Correctomundo!"
  , "Cowabunga!"
  , "Crap on a stick!"
  , "Damn Skippy."
  , "Damn straight!"
  , "Damn!"
  , "Dang!"
  , "Darn tootin'!"
  , "Dayumn!"
  , "Dear lord!"
  , "Dip me in honey and throw me to the lesbians!"
  , "Do you...Yahoo!?"
  , "Doodlebugs!"
  , "Easy does it!"
  , "Easy peasy lemon squeezy!"
  , "Eat my shorts!"
  , "Eureka!"
  , "Excellent!"
  , "Fabulous!"
  , "Fancy that!"
  , "Fantastic!"
  , "Far out!"
  , "Fiddledeedee!"
  , "Fiddlesticks!"
  , "Finally!"
  , "Fire in the hole!"
  , "Fo shizzle my nizzle!"
  , "For crying out loud!"
  , "For fuck’s sake!"
  , "For gods sake!"
  , "For real!"
  , "Foxy!"
  , "Front and center!"
  , "Fuck a duck!"
  , "Fuck me sideways!"
  , "Fuck yeah!"
  , "Fuck-a-doodle-doo!"
  , "Fucking hell!"
  , "Gee whillikers!"
  , "Gee whiz!"
  , "Geez Louise!"
  , "Geez!"
  , "Geronimo!"
  , "Get out of town!"
  , "Giddyup!"
  , "Glittering!"
  , "Glorious!"
  , "Go ahead, make my day."
  , "God speed!"
  , "Golly!"
  , "Good call!"
  , "Good god!"
  , "Good gravy!"
  , "Good grief!"
  , "Good to go!"
  , "Goodness gracious!"
  , "Got Milk?"
  , "Grand!"
  , "Great Scott!"
  , "Great balls of fire!"
  , "Great gogglie wogglie!"
  , "Great googly moogly!"
  , "Great!"
  , "Groovy!"
  , "Hail to the king, baby!"
  , "Hakuna Matata."
  , "Hallelujah!"
  , "Hasta la vista, baby."
  , "Have it your way."
  , "Hee haw!"
  , "Hell yeah!"
  , "Here goes nothing..."
  , "Here we go again..."
  , "Hip, hip, hooray!"
  , "Hocus pocus!"
  , "Hold on to your butts!"
  , "Holy batshit, Robin!"
  , "Holy bat, shitman!"
  , "Holy cow!"
  , "Holy guacamole!"
  , "Holy jumping mother o’God in a side-car with chocolate jimmies and a lobster bib!"
  , "Holy jumping weasel critters on a hot cross bun!"
  , "Holy mackerel!"
  , "Holy mary mother of god!"
  , "Holy moses!"
  , "Holy smokes!"
  , "Hot damn!"
  , "Hot diggety!"
  , "Hot diggity dog!"
  , "How you doin'?"
  , "Howdy doody!"
  , "Hurrah!"
  , "I love the smell of napalm in the morning."
  , "I'll be back."
  , "I'll drink to that!"
  , "I'm as mad as hell, and I'm not going to take this anymore!"
  , "I'm loving it!"
  , "I'm the king of the world!"
  , "Impressive!"
  , "In your face!"
  , "It's alive! It's alive!"
  , "It's showtime!"
  , "It's time to kick ass and chew bubblegum, and I'm all out of gum..."
  , "It’s over, Johnny."
  , "I’m too old for this shit."
  , "Jeepers creepers!"
  , "Jolly good show!"
  , "Jumping Jesus on a pogo stick!"
  , "Just Do It."
  , "Just when I thought I was out, they pull me back in."
  , "Ka-boom!"
  , "Ka-ching!"
  , "Kaboom!"
  , "Kapow!"
  , "Keepin' it real."
  , "Kick ass!"
  , "Lackadaisy!"
  , "Land ahoy!"
  , "Leaping lizards!"
  , "Let's rock!"
  , "Live long and prosper."
  , "Lo and behold!"
  , "Lock and load!"
  , "Love this shit!"
  , "Lovely!"
  , "Made you look!"
  , "Mamma mia!"
  , "Marvelous!"
  , "May the Force be with you."
  , "Mazzeltov!"
  , "Mother of god!"
  , "Muahuhaha!"
  , "Namaste!"
  , "Neato burrito!"
  , "Never say never!"
  , "Nice one!"
  , "No diggity!"
  , "No kidding!"
  , "No problemo!"
  , "No probs!"
  , "No shit!"
  , "No shit, Sherlock!"
  , "No soup for you!"
  , "No way!"
  , "OK, boomer!"
  , "OMG!"
  , "Oh goody!"
  , "Oh lordy!"
  , "Oh, behave!"
  , "Okey dokey!"
  , "On your marks, set, go!"
  , "Opulent!"
  , "Pat on the back!"
  , "Patootie!"
  , "Peace out!"
  , "Peace!"
  , "Peekaboo!"
  , "Perfect!"
  , "Pobody's nerfect."
  , "Poof!"
  , "Praise the Lord!"
  , "Psst..."
  , "Quel surprise!"
  , "ROTFLMAO."
  , "Radical!"
  , "Ravishing!"
  , "Ready, aim, fire!"
  , "Resistance is futile."
  , "Right!"
  , "Right-O!"
  , "Right-on!"
  , "Righteous!"
  , "Rise and shine!"
  , "Roads? Where we're going we don't need roads."
  , "Rock on!"
  , "Roger that!"
  , "Roger!"
  , "Sacre bleu!"
  , "Send it!"
  , "Set phasers to stun!"
  , "Shazaam!"
  , "Ship ahoy!"
  , "Shit is getting real!"
  , "Shit just got real."
  , "Shit yeah!"
  , "Shit's on fire, yo."
  , "Shiver me timbers!"
  , "Shots fired!"
  , "Slap my ass and call me Judy!"
  , "Smell ya later!"
  , "Snakes alive!"
  , "So easy a caveman can do it."
  , "So long, and thanks for all the fish!"
  , "Splendid!"
  , "Splendiferous!"
  , "Spoiler alert!"
  , "Stay classy!"
  , "Stunning!"
  , "Sublime!"
  , "Suck me sideways!"
  , "Sumptuous!"
  , "Superb!"
  , "Sweet Sassy Molassy!"
  , "Sweet Zombie Jesus!"
  , "Swell!"
  , "Ta ta for now!"
  , "Ta-da!"
  , "That's beautiful, man."
  , "The cake is a lie."
  , "There is still hope for humanity."
  , "There ya go!"
  , "There's a snake in my boot."
  , "Time to nut up or shut up."
  , "To infinity and beyond!"
  , "To the Batmobile!"
  , "Touché!"
  , "Tough titty said the kitty!"
  , "Uh-oh, Spaghetti-o!"
  , "Upsadaisy!"
  , "Va-va-voom!"
  , "Voilà!"
  , "Watermelon sugar high!"
  , "Way to go!"
  , "We're not in Kansas anymore."
  , "Well, I’ll be a monkey’s bare-assed uncle."
  , "Whaddayaknow?"
  , "Wham, bam, thank you ma'am!"
  , "What's cookin' good lookin'?"
  , "Whatever creams your twinkie!"
  , "Whatever floats your boat!"
  , "Whatever."
  , "Whazzup?"
  , "Whoop-de-doo!"
  , "Whoopee!"
  , "Who’s your daddy?"
  , "Why so serious?"
  , "Wink wink nudge nudge..."
  , "Woohoo!"
  , "Woot woot!"
  , "Word!"
  , "Wow!"
  , "YES!!!"
  , "Yabba dabba doo!"
  , "Yeah!"
  , "Yee-haw!"
  , "Yeppers!"
  , "Yessiree!"
  , "Yessiree, Bob."
  , "Yippee!"
  , "Yippie-ki-yay, motherfucker!"
  , "You can't handle the truth."
  , "You have no clue what you re doing, do you?"
  , "You know it!"
  , "You know what the real tragedy is? I'm not even supposed to be here today!"
  , "You've got to ask yourself one question: Do I feel lucky? Well, do ya punk?"
  , "You’re gonna need a bigger boat."
  , "Yummy!"
  ]

main :: IO()
-- Print out the interjection at the index given by randomRIO
main = putStrLn . (ijs !!) =<< randomRIO (0, length ijs - 1)
