import System.Random

ijs =
  [ "Abracadabra!"
  , "All good in the hood!"
  , "All hands on deck!"
  , "All righty!"
  , "Allah Akbar!"
  , "Aloha!"
  , "Alrighty then!"
  , "Alrighty!"
  , "Amen!"
  , "Amirite?"
  , "Attaboy!"
  , "Awesome!"
  , "Aww!"
  , "Ba da bing ba da boom!"
  , "Ba dum tish!"
  , "Bam!"
  , "Bejesus!"
  , "Bingo!"
  , "Bish bash bosh!"
  , "Bitchin'!"
  , "Bite my shiny metal ass!"
  , "Blimey!"
  , "Blow me over!"
  , "Blow me tight!"
  , "Bombs away!"
  , "Boo-yah!"
  , "Boom shaka laka!"
  , "Booyah!"
  , "Bottoms up!"
  , "Bravissimo!"
  , "Brilliant!"
  , "Butter my butt and call me a biscuit!"
  , "By golly!"
  , "Calm your tits!"
  , "Capiche?"
  , "Caramba!"
  , "Carpe diem!"
  , "Centerfold!"
  , "Check!"
  , "Cheerioh!"
  , "Cheers!"
  , "Clickety clackety!"
  , "Cockadoodledoo!"
  , "Cool bananas!"
  , "Cool!"
  , "Cootchie-cootchie-coo!"
  , "Correctomundo!"
  , "Cowabunga!"
  , "Crap on a stick!"
  , "Damn Skippy"
  , "Damn straight!"
  , "Damn!"
  , "Dang!"
  , "Darn tootin'!"
  , "Dayumn!"
  , "Dear lord!"
  , "Dip me in honey and throw me to the lesbians!"
  , "Easy does it!"
  , "Eat my shorts!"
  , "Eureka!"
  , "Excellent!"
  , "Fabulous!"
  , "Fancy that!"
  , "Fantastic!"
  , "Far out!"
  , "Fiddledeedee!"
  , "Fiddlesticks!"
  , "Finally!"
  , "Fire in the hole!"
  , "Fo shizzle my nizzle!"
  , "For cryin out loud!"
  , "For fuck’s sake!"
  , "For gods sake!"
  , "For real!"
  , "Foxy!"
  , "Front and center!"
  , "Fuck a duck!"
  , "Fuck me sideways!"
  , "Fuck yeah!"
  , "Fuck-a-doodle-doo!"
  , "Fucking hell!"
  , "Gee whillikers!"
  , "Gee whiz!"
  , "Geez Louise!"
  , "Geez!"
  , "Geronimo!"
  , "Get out of town!"
  , "Giddyup!"
  , "Glittering!"
  , "Glorious!"
  , "God speed!"
  , "Golly!"
  , "Good call!"
  , "Good god!"
  , "Good gravy!"
  , "Good grief!"
  , "Good to go!"
  , "Goodness gracious!"
  , "Grand!"
  , "Great Scott!"
  , "Great balls of fire!"
  , "Great gogglie wogglie!"
  , "Great!"
  , "Groovy!"
  , "Hail to the king, baby!"
  , "Hallelujah!"
  , "Hasta la vista, baby!"
  , "Hee haw!"
  , "Hell yeah!"
  , "Here goes nothing..."
  , "Here we go again..."
  , "Hip, hip, hooray!"
  , "Hocus pocus!"
  , "Holy cow!"
  , "Holy guacamole!"
  , "Holy mackerel!"
  , "Holy mary mother of god!"
  , "Holy moses!"
  , "Holy smokes!"
  , "Hot damn!"
  , "Hot diggety!"
  , "Hot diggity dog!"
  , "How you doin'?"
  , "Howdy doody!"
  , "Hurrah!"
  , "I'll drink to that!"
  , "I'm the king of the world!"
  , "Impressive!"
  , "In your face!"
  , "Jeepers creepers!"
  , "Jolly good show!"
  , "Jumping Jesus on a pogo stick!"
  , "Ka-boom!"
  , "Ka-ching!"
  , "Kaboom!"
  , "Kapow!"
  , "Kick ass!"
  , "Lackadaisy!"
  , "Land ahoy!"
  , "Leaping lizards!"
  , "Let's rock!"
  , "Live long and prosper!"
  , "Lo and behold!"
  , "Lock and load!"
  , "Love this shit!"
  , "Lovely!"
  , "Made you look!"
  , "Mamma mia!"
  , "Marvelous!"
  , "Mazzeltov!"
  , "Mother of god!"
  , "Muahuhaha!"
  , "Namaste!"
  , "Neato burrito!"
  , "Never say never!"
  , "Nice one!"
  , "No diggity!"
  , "No kidding!"
  , "No problemo!"
  , "No probs!"
  , "No shit!"
  , "No shit, Sherlock!"
  , "No soup for you!"
  , "No way!"
  , "OK, boomer!"
  , "OMG!"
  , "Oh goody!"
  , "Oh lordy!"
  , "Okey dokey!"
  , "On your marks, set, go!"
  , "Opulent!"
  , "Pat on the back!"
  , "Patootie!"
  , "Peace out!"
  , "Peace!"
  , "Peekaboo!"
  , "Perfect!"
  , "Poof!"
  , "Praise the Lord!"
  , "Psst..."
  , "Quel surprise!"
  , "ROTFLMAO."
  , "Radical!"
  , "Ravishing!"
  , "Ready, aim, fire!"
  , "Resistance is futile!"
  , "Right!"
  , "Right-O!"
  , "Right-on!"
  , "Righteous!"
  , "Rise and shine!"
  , "Rock on!"
  , "Roger that!"
  , "Roger!"
  , "Sacre bleu!"
  , "Send it!"
  , "Set phasers to stun!"
  , "Shazaam!"
  , "Ship ahoy!"
  , "Shit is getting real!"
  , "Shit yeah!"
  , "Shiver me timbers!"
  , "Shots fired!"
  , "Slap my ass and call me Judy!"
  , "Smell ya later!"
  , "Snakes alive!"
  , "So long, and thanks for all the fish!"
  , "Splendid!"
  , "Splendiferous!"
  , "Spoiler alert!"
  , "Stay classy!"
  , "Stunning!"
  , "Sublime!"
  , "Sumptuous!"
  , "Superb!"
  , "Swell!"
  , "Ta ta for now!"
  , "Ta-da!"
  , "That's beautiful, man."
  , "There is still hope for humanity!"
  , "There ya go!"
  , "To the Batmobile!"
  , "Touché!"
  , "Tough titty said the kitty!"
  , "Uh-oh, Spaghetti-o!"
  , "Upsadaisy!"
  , "Va-va-voom!"
  , "Voilà!"
  , "Watermelon sugar high!"
  , "Way to go!"
  , "We're not in Kansas anymore!"
  , "Whaddayaknow?"
  , "Wham, bam, thank you ma'am!"
  , "What's cookin' good lookin'?"
  , "Whatever creams your twinkie!"
  , "Whatever floats your boat!"
  , "Whatever."
  , "Whazzup?"
  , "Whoop-de-doo!"
  , "Whoopee!"
  , "Who’s your daddy?"
  , "Wink wink nudge nudge..."
  , "Woohoo!"
  , "Woot woot!"
  , "Word!"
  , "Wow!"
  , "YES!!!"
  , "Yabba dabba doo!"
  , "Yeah!"
  , "Yee-haw!"
  , "Yeppers!"
  , "Yessiree!"
  , "Yessiree, Bob!"
  , "Yippee!"
  , "You have no clue what you re doing, do you?"
  , "You know it!"
  , "You know what the real tragedy is? I'm not even supposed to be here today!"
  , "Yummy!"
  ]

main :: IO()
-- Print out the interjection at the index given by randomRIO
main = putStrLn . (ijs !!) =<< randomRIO (0, length ijs - 1)
